---

- hosts: hadoop-node
  become: true
  tasks:

    - name: remove openjdk-11-jdk
      apt:
        name: "{{ jdk_package  }}, {{ jdk_depend  }}"
        state: absent    

    - name: stop hdfs daemons
      ansible.builtin.shell: "{{ item }}"
      ignore_errors: true
      with_items:
        - "{{ hadoop_sbin }}/hadoop-daemon.sh stop namenode"
        - "{{ hadoop_sbin }}/hadoop-daemon.sh stop secondarynamenode"
        - "{{ hadoop_sbin }}/hadoop-daemon.sh stop datanode"

    - name: stop yarn daemons
      ansible.builtin.shell: "{{ item }}"
      ignore_errors: yes
      with_items:
        - "{{ hadoop_sbin }}/yarn-daemon.sh stop resourcemanager"
        - "{{ hadoop_sbin }}/yarn-daemon.sh stop nodemanager"

    - name: remove hadoop2 directory
      file:
        path: "{{ usr_local_hadoop_dir  }}"
        state: absent

#  - name: remove hadoop2 tar
#    file:
#     path: "{{ hadoop_tar }}"
#     state: absent

    - name: remove directories hadoop_store, namenode, datanode
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ hadoop_store }}"
        - "{{ hadoop_log_dir }}"
